name:                foreach
version:             0.1.0.0
synopsis:            Streaming data and loops built on stream fusion
description:         See README.md
homepage:            https://github.com/snoyberg/foreach#readme
license:             MIT
author:              Michael Snoyman
maintainer:          michael@snoyman.com
copyright:           2017 FP Complete
category:            Streaming, Data
extra-source-files:
- README.md
- ChangeLog.md

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs:      src
  exposed-modules:
  - ForEach
  - ForEach.Internal
  - ForEach.Prelude
  ghc-options:
  - -O2

benchmarks:
  foreach-bench:
    source-dirs:    bench
    main:           Main.hs
    dependencies:
    - foreach
    - criterion
    - vector
    ghc-options:
    - -O2
